spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/guruguru?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1111

server:
  frontEnd: http://localhost:3000
  servlet:
    context-path: /api


cloud:
  aws:
    credentials:
      accessKey: access key
      secretKey: secret key
    s3:
      bucket: ns-union
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVna
